export const eventsList = [
  {
    key: 1,
    isRegistrationOpen: false,
    id: 'vrc',
    name: 'VJTI Robotics Challenge(VRC)',
    description:
      'The UNITY gaming engine will be used to recreate an arena with obstacles and tasks based on a theme. Participants will have to compete with the bots they have created.',
    url: '/register/event/vrc',
    imageSrc: '/events/vrc.png',
    date: '23rd, 24th, 25th and 26th Feb 2023',
    venue: 'Unity game engine',
    onSiteReg: true,
    discord: '',
    platformLink: '',
    pdfLink:
      'https://drive.google.com/file/d/1NnGyQ2Oe595JnVRNEgl9uJY_z2zm3PLj/view',
    minSize: 1,
    maxSize: 3,
    notice:
      'Unity Game Engine Workshop for building a keyboard bot and a doubt clearing session for this event has been organised. It is mandatory to attend the workshop for participating in this event. You can register in the Workshops section.',
  },
  {
    key: 2,
    isRegistrationOpen: false,
    id: 'robomaze',
    name: 'Robomaze',
    description:
      'The UNITY gaming engine will be used to mimic an arena. Users will be able to design their own bots to navigate through a maze.',
    url: '/register/event/robomaze',
    imageSrc: '/events/robomaze.jpg',
    date: '23rd, 24th and 25th and 26th Feb 2023',
    venue: 'Unity game engine',
    onSiteReg: true,
    discord: '',
    platformLink: '',
    pdfLink:
      'https://drive.google.com/file/d/1nlhaKKrOAI3e5ngR6KIMlbzcB-KUMl9t/view',
    minSize: 1,
    maxSize: 2,
    notice:
      'Unity Game Engine Workshop for building a keyboard bot and a doubt clearing session for this event has been organised. It is mandatory to attend the workshop for participating in this event. You can register in the Workshops section.',
  },
  {
    key: 3,
    isRegistrationOpen: false,
    id: 'monster_arena',
    name: 'Monster Arena',
    description:
      'The UNITY gaming engine will be used to mimic an arena. Users will be able to construct their own bots, which will be structuraly and technically tested. The controllers abilities are also put to test.',
    url: '/register/event/monster-arena',
    imageSrc: '/events/monster-arena.png',
    date: '24th and 25th and 26th Feb 2023',
    venue: 'Unity game engine',
    onSiteReg: true,
    discord: '',
    platformLink: '',
    pdfLink:
      'https://drive.google.com/file/d/1gLOEAUkzv2exJsl9p0bY6dxYDDPms8vE/view',
    minSize: 1,
    maxSize: 2,
    notice:
      'Unity Game Engine Workshop for building a keyboard bot and a doubt clearing session for this event has been organised. It is mandatory to attend the workshop for participating in this event. You can register in the Workshops section.',
  },
  {
    key: 4,
    isRegistrationOpen: false,
    id: 'fnf',
    name: 'Fast N Furious',
    description:
      'The UNITY gaming engine will be used to mimic an arena. Users will be able to develop their own bots and race against other players on a well-designed track with numerous obstacles.',
    url: '/register/event/fnf',
    imageSrc: '/events/fnf.png',
    date: '24th and 25th and 26th Feb 2023',
    venue: 'Unity game engine',
    onSiteReg: true,
    discord: '',
    platformLink: '',
    pdfLink:
      'https://drive.google.com/file/d/1VksUPH68RbmPmQvJegSzxpkJBCi51-7q/view',
    minSize: 1,
    maxSize: 1,
  },
  {
    key: 5,
    isRegistrationOpen: false,
    id: 'escape_room',
    name: 'Escape Room',
    description: 'A brain teasing treasure hunt based on a theme.',
    url: '/register/event/escape-room',
    imageSrc: '/events/escape-room.png',
    date: '24th Feb 2023',
    venue: 'Email Submission',
    onSiteReg: true,
    discord: '',
    platformLink: '',
    pdfLink:
      'https://drive.google.com/file/d/1vmmcIJy5lo30PS3dp_AFtAKclrOCjWnJ/view',
    minSize: 2,
    maxSize: 4,
  },
  {
    key: 6,
    isRegistrationOpen: false,
    id: 'smart_city',
    name: 'Smart City',
    description: 'Design a smart city using an online sketch-up site.',
    url: '/events/smart-city.png',
    imageSrc: '/events/smart-city.png',
    date: '24th Feb 2023',
    venue: 'Online Sketchup Server ',
    onSiteReg: true,
    discord: '',
    platformLink: '',
    pdfLink:
      'https://drive.google.com/file/d/1XIyPetEd_Ns_7gcffH4UKwGJs5KWnzOA/view',
    minSize: 1,
    maxSize: 4,
  },
  {
    key: 7,
    isRegistrationOpen: false,
    id: 'peruse',
    name: 'Peruse',
    description:
      'Quiz based on logical and analytical thinking + cryptography.',
    url: '/register/event/peruse',
    imageSrc: '/events/peruse.png',
    date: '25th and 26th Feb 2023',
    venue: 'Email Submission',
    onSiteReg: true,
    discord: '',
    platformLink: '',
    pdfLink:
      'https://drive.google.com/file/d/16qRMYOuuOQ2Q5CZ9FtcpMBf6OZ11kjhP/view',
    minSize: 1,
    maxSize: 3,
  },
  {
    key: 8,
    isRegistrationOpen: false,
    id: 'hackathon',
    name: 'Techno Hack',
    description:
      'A sprint-style event focused on collaborative programming, in which teams will be given a problem statement and their goal will be to develop a protoype within 24hrs.',
    url: '/register/event/hackathon',
    imageSrc: '/events/hackathon.png',
    date: '23rd and 24th Feb (24 hrs)',
    venue: ' ',
    onSiteReg: false,
    discord: '',
    platformLink:
      'https://dare2compete.com/hackathon/technohack2023-vjti-technovanza-2021-22-veermata-jijabai-technological-institute-vjti-mumbai-258562',
    pdfLink:
      'https://drive.google.com/file/d/12nM8nrmhE7h7DpEe4NsxafBBmkxbevov/view',
    minSize: 2,
    maxSize: 4,
  },
  {
    key: 9,
    isRegistrationOpen: false,
    id: 'cway_javaguru',
    name: 'Java-C Guru',
    description:
      'This event consists of various levels with increasing difficulties incorporated with a fascinating theme. There are variety of question patterns challenging each area knowledge. ',
    url: '/register/event/cway-javaguru',
    imageSrc: '/events/cjavaguru.png',
    date: '17th Feb 2023',
    venue: 'Email Submission',
    onSiteReg: true,
    discord: '',
    platformLink: '',
    pdfLink:
      'https://drive.google.com/file/d/1aG7YanH0gKuhGNf0jBxRyh5I2lvoukx3/view',
    minSize: 1,
    maxSize: 1,
  },
  {
    key: 10,
    isRegistrationOpen: false,
    id: 'ultimate_coder',
    name: 'Ultimate Coder',
    description: 'Questions based on an all round coding challenge.',
    url: '/register/event/ultimate-coder',
    imageSrc: '/events/ultimate-coder.png',
    date: '17th Feb 2023',
    venue: 'Email Submission',
    onSiteReg: true,
    discord: '',
    platformLink: '',
    pdfLink:
      'https://drive.google.com/file/d/1TKNWrCgNm8oTOL-bdjE6nIBTB90WKjEC/view',
    minSize: 1,
    maxSize: 2,
  },
  {
    key: 11,
    isRegistrationOpen: false,
    id: 'technohunt_sherlocked',
    name: 'Sherlocked-The Hunt',
    description:
      "Treasure Hunt based on programming and an event based on Sherlock Holmes' mysteries.",
    url: '/register/event/technohunt-sherlocked',
    imageSrc: '/events/sherlocked.png',
    date: '25th and 26th Feb 2023',
    venue: 'Email Submission',
    onSiteReg: true,
    discord: '',
    platformLink: '',
    pdfLink:
      'https://drive.google.com/file/d/1LMJ5pZGBexAeHFvuiIAFflUtDO0IOCvo/view',
    minSize: 1,
    maxSize: 1,
  },
  {
    key: 12,
    isRegistrationOpen: false,
    id: 'codestorm',
    name: 'Codestorm',
    description: 'Competitive coding contest.',
    url: '/register/event/codestorm',
    imageSrc: '/events/codestorm.png',
    date: '25th and 26th Feb 2023',
    venue: 'Email Submission',
    onSiteReg: true,
    discord: '',
    platformLink: '',
    pdfLink:
      'https://drive.google.com/file/d/1sIgovYRhfyR5x2JLnOu0ZMQPLbkXc7-n/view',
    minSize: 1,
    maxSize: 2,
  },
  {
    key: 13,
    isRegistrationOpen: false,
    id: 'vmco',
    name: 'VMCO Cubing Event',
    description:
      'Annual Cubing competition where people from all over the country come and compete.',
    url: '/register/event/vmco',
    imageSrc: '/events/vmco.png',
    date: '24th and 25th and 26th Feb 2023',
    venue: 'Online',
    onSiteReg: true,
    discord: '',
    platformLink: '',
    pdfLink:
      'https://drive.google.com/file/d/1g8DX8JhAy-sJW_9jXsI9ogs16nkC9uIn/view',
    minSize: 1,
    maxSize: 1,
  },
  {
    key: 14,
    isRegistrationOpen: false,
    id: 'ctf',
    name: 'Capture the Flag',
    description:
      "CTF is a cyber-security event where you'll have to break programs, sneakily hack systems, intercept and decrypt hidden messages, reverse engineer, or do whatever it takes to find a certain hidden 'flag' and retrieve it.",
    url: '/register/event/ctf',
    imageSrc: '/events/ctf.png',
    date: '25th and 26th Feb 2023',
    venue: 'Online',
    onSiteReg: true,
    discord: '',
    platformLink: '',
    pdfLink:
      'https://drive.google.com/file/d/1wN1PULHAW4CAO9q1pmdScNjbyPfd6ER4/view',
    minSize: 1,
    maxSize: 2,
  },
  {
    key: 15,
    isRegistrationOpen: false,
    id: 'uiux',
    name: 'UI/UX Challenge',
    description:
      'A UI/UX Challenge revolving around the world of web development, a perfect platform for you to showcase your creativity and design thinking. A challenge that provides you with an opportunity to take a peek into the world of design and the freedom to experiment.',
    url: '/register/event/ui-x',
    imageSrc: '/events/ui-ux.png',
    date: '17th Feb 2023',
    venue: 'Online',
    onSiteReg: true,
    discord: '',
    platformLink: '',
    pdfLink:
      'https://drive.google.com/file/d/1Pu_hiHvae-qWdPlYr_OQt6fjARjW2KWK/view',
    minSize: 1,
    maxSize: 1,
  },
];
